services: #here we will list all the containers we want 

 postgres:
  image: postgres:16-alpine
  container_name: openhabitat-postgres
  restart: unless-stopped
  environment:
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=chirpstack
  volumes:
   - ./data/chirpstack-postgres:/var/lib/postgresql/data
  networks:
   - openhabitat

 timescaledb: #the name of the database
  image: timescale/timescaledb:latest-pg14 #this tells the docker to download and run TimescaleDB image
  container_name: database
  environment:
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   POSTGRES_DB: ${POSTGRES_DB}

  ports:
   - "5432:5432" #Expose PostgreSQL on this port
  networks:
   - openhabitat
  volumes:
   - timescale_data:/var/lib/postgresql/data #timescale_data is the volume name and the rest is where PostgreSQL stores its data inside the container

 redis:
  image: redis:7-alpine
  container_name: openhabitat-redis
  restart: unless-stopped
  networks:
   - openhabitat


 grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
   - "3000:3000"
  networks:
   - openhabitat
  volumes:
   - grafana_data:/var/lib/grafana

 mosquitto:
  image: eclipse-mosquitto:2
  container_name: openhabitat-mosquitto
  restart: unless-stopped
  ports:
   - "1883:1883"
  networks:
   - openhabitat
  volumes:
   - ./config/mosquitto:/mosquitto/config

 chirpstack-gateway-bridge:
  image: chirpstack/chirpstack-gateway-bridge:4
  container_name: openhabitat-gateway-bridge
  restart: unless-stopped
  ports:
   - "1700:1700/udp"
  volumes:
   - ./config/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
  networks:
   - openhabitat

 chirpstack:
  image: chirpstack/chirpstack:4
  container_name: openhabitat-chirpstack
  restart: unless-stopped
  command: -c /etc/chirpstack
  ports:
   - "8080:8080"
  volumes:
   - ./config/chirpstack:/etc/chirpstack
  networks:
   - openhabitat 

volumes:
 timescale_data: #decalring the volume
 grafana_data:
   #Volumes are important so that even when we restart the containers ther is bo data loss

networks:     #DNS resolution, all containers need to be on the same network in order to find each other by name.
  openhabitat:
    driver: bridge
